#spring.cloud.function.definition:
#  - processActiveDomains
#  - processInActiveDomains

spring:
  cloud:
    stream:
      function:
        definition:
          - processActiveDomains
          - processInActiveDomains
      bindings:
        processActiveDomains-in-0:
          destination: test-webdomains
        processActiveDomains-out-0:
          destination: test-active-domains
        processInActiveDomains-in-0:
          destination: test-webdomains
        processInActiveDomains-out-0:
          destination: test-inactive-domains

      kafka:
#        producer:
#          properties.spring.json.trusted.packages: "com.service.generator.bean"
#        consumer:
#          properties.spring.json.trusted.packages: "com.service.generator.bean"
        binder:
          brokers:
            - localhost:9091
#            - localhost:9092
          #auto-create-topics: true
          configuration:
            auto.offset.reset: latest

        bindings:
          processActiveDomains-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            destination: test-webdomains
          processActiveDomains-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
            destination: test-active-domains
          processInActiveDomains-in-0:
            consumer.configuration.value.deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
            destination: test-webdomains
          processInActiveDomains-out-0:
            producer.configuration.value.serializer: org.springframework.kafka.support.serializer.JsonSerializer
            destination: test-inactive-domains

